# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: dolphinnext
channels:
    - conda-forge
    - bioconda
    - anaconda
    - r
    - defaults
dependencies:
    - python>=3.9
    - r>=4.1
    - minimap2=2.24
    - biopython=1.79
    - samtools=1.15.1  
    - pysam>=0.19.0
    - r-dplyr=1.0.8
    - r-ggplot2=3.3.5
    - r-gridbase=0.4_7
    - r-gridextra=2.3